// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BancaCore.Domain.Entities
{
    /// <summary>
    /// Entidad Cliente - Representa un cliente del banco en el dominio de negocio.
    /// </summary>
    public class Cliente
    {
        /// <summary>
        /// Identificador único del cliente
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Nombre completo del cliente
        /// </summary>
        public string Nombre { get; set; }

        /// <summary>
        /// Fecha de nacimiento del cliente
        /// </summary>
        public DateOnly FechaNacimiento { get; set; }

        /// <summary>
        /// Sexo del cliente (M: Masculino, F: Femenino)
        /// </summary>
        public string Sexo { get; set; }

        /// <summary>
        /// Ingresos mensuales del cliente en la moneda local
        /// </summary>
        public decimal Ingresos { get; set; }

        /// <summary>
        /// Colección de cuentas bancarias asociadas al cliente
        /// Relación uno a muchos con la entidad CuentaBancaria
        /// </summary>
        public virtual ICollection<CuentaBancaria> CuentasBancaria { get; set; } = new List<CuentaBancaria>();
    }
}