// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BancaCore.Domain.Entities;

public partial class Clientes
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public string Sexo { get; set; }

    public decimal Ingresos { get; set; }

    public virtual ICollection<CuentasBancarias> CuentasBancaria { get; set; } = new List<CuentasBancarias>();
}