// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;

namespace BancaCore.Domain.Entities
{
    /// <summary>
    /// Entidad CuentaBancaria - Representa una cuenta bancaria en el dominio de negocio.
    /// </summary>
    public partial class CuentaBancaria
    {
        /// <summary>
        /// Identificador único de la cuenta bancaria
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Número de cuenta único asignado a la cuenta bancaria
        /// </summary>
        public string NumeroCuenta { get; set; }

        /// <summary>
        /// Identificador del cliente propietario de la cuenta
        /// Clave foránea que relaciona con la entidad Cliente
        /// </summary>
        public int ClienteId { get; set; }

        /// <summary>
        /// Saldo actual disponible en la cuenta bancaria
        /// </summary>
        public decimal Saldo { get; set; }

        /// <summary>
        /// Referencia al cliente propietario de la cuenta
        /// Relación muchos a uno con la entidad Cliente
        /// </summary>
        public virtual Cliente Cliente { get; set; }

        /// <summary>
        /// Colección de transacciones realizadas en esta cuenta
        /// Relación uno a muchos con la entidad Transaccion
        /// </summary>
        public virtual ICollection<Transaccion> Transacciones { get; set; } = new List<Transaccion>();
    }
}