// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BancaCore.Domain.Entities;

public partial class CuentasBancarias
{
    public int Id { get; set; }

    public string NumeroCuenta { get; set; }

    public int ClienteId { get; set; }

    public decimal Saldo { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<Transacciones> Transacciones { get; set; } = new List<Transacciones>();
}