// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BancaCore.Domain.Entities;

public partial class Transacciones
{
    public int Id { get; set; }

    public int CuentaId { get; set; }

    public string TipoTransaccion { get; set; }

    public string Descripcion { get; set; }

    public decimal Monto { get; set; }

    public decimal SaldoPosterior { get; set; }

    public DateTime? FechaTransaccion { get; set; }

    public virtual CuentasBancarias Cuenta { get; set; }
}