// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace BancaCore.Domain.Entities
{
    /// <summary>
    /// Entidad Transaccion - Representa una operación financiera en una cuenta bancaria.
    /// </summary>
    public partial class Transaccion
    {
        /// <summary>
        /// Identificador único de la transacción
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Identificador de la cuenta bancaria donde se realizó la transacción
        /// Clave foránea que relaciona con la entidad CuentaBancaria
        /// </summary>
        public int CuentaId { get; set; }

        /// <summary>
        /// Tipo de transacción realizada (Depósito, Retiro, Transferencia, etc.)
        /// </summary>
        public string TipoTransaccion { get; set; }

        /// <summary>
        /// Descripción detallada de la transacción
        /// </summary>
        public string Descripcion { get; set; }

        /// <summary>
        /// Monto de la transacción (positivo para ingresos, negativo para egresos)
        /// </summary>
        public decimal Monto { get; set; }

        /// <summary>
        /// Saldo resultante en la cuenta después de realizar la transacción
        /// </summary>
        public decimal SaldoPosterior { get; set; }

        /// <summary>
        /// Fecha y hora en que se realizó la transacción
        /// </summary>
        public DateTime? FechaTransaccion { get; set; }

        /// <summary>
        /// Referencia a la cuenta bancaria donde se realizó la transacción
        /// Relación muchos a uno con la entidad CuentaBancaria
        /// </summary>
        public virtual CuentaBancaria Cuenta { get; set; }
    }
}