// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BancaCore.Common.Interfaces;
using BancaCore.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace BancaCore.Persistence;

/// <summary>
/// Contexto de base de datos para la aplicación bancaria - Capa de Infraestructura
/// Implementa la interfaz IBancaDbContext definida en la capa de aplicación
/// </summary>
public partial class BancaDbContext : DbContext, IBancaDbContext
{
    public BancaDbContext(DbContextOptions<BancaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<CuentaBancaria> CuentasBancarias { get; set; }

    public virtual DbSet<Transaccion> Transacciones { get; set; }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        return await base.SaveChangesAsync(cancellationToken);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC0763C67761");

            entity.Property(e => e.Ingresos).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
        });

        modelBuilder.Entity<CuentaBancaria>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CuentasB__3214EC070E2FD987");

            entity.HasIndex(e => e.NumeroCuenta, "UQ__CuentasB__E039507BD62C0B96").IsUnique();

            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Saldo).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.CuentasBancaria)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CuentasBa__Clien__4D94879B");
        });

        modelBuilder.Entity<Transaccion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Transacc__3214EC077210F304");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaTransaccion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Monto).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SaldoPosterior).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TipoTransaccion)
                .IsRequired();

            entity.HasOne(d => d.Cuenta).WithMany(p => p.Transacciones)
                .HasForeignKey(d => d.CuentaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Transacci__Cuent__52593CB8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}