// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using BancaCore.Domain.Entities;
using BancaCore.Common.Interfaces;

namespace BancaCore.Persistence;

public partial class BancaDbContext : DbContext,IBancaDbContext
{
    public BancaDbContext(DbContextOptions<BancaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }

    public virtual DbSet<Transacciones> Transacciones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC0763C67761");

            entity.Property(e => e.Ingresos).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
        });

        modelBuilder.Entity<CuentasBancarias>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CuentasB__3214EC070E2FD987");

            entity.HasIndex(e => e.NumeroCuenta, "UQ__CuentasB__E039507BD62C0B96").IsUnique();

            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Saldo).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.CuentasBancaria)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CuentasBa__Clien__4D94879B");
        });

        modelBuilder.Entity<Transacciones>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Transacc__3214EC077210F304");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaTransaccion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Monto).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SaldoPosterior).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TipoTransaccion)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Cuenta).WithMany(p => p.Transacciones)
                .HasForeignKey(d => d.CuentaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Transacci__Cuent__52593CB8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}