<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <AssemblyName>BancaCore.Common</AssemblyName>
	  <RootNamespace>BancaCore.Common</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.10.0" />
		<PackageReference Include="Microsoft.ASpNetCore.Http" Version="2.2.2" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.DependencyValidation.Analyzers" Version="0.11.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
	</ItemGroup>
	
</Project>